# Generated by Django 4.2.7 on 2023-11-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='dec',
            new_name='desc',
        ),
    ]
