# Generated by Django 4.2.7 on 2023-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_dec_team_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='imgg',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
